version: 2.1

jobs:
  robonito-tests:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Trigger Robonito tests
          command: |

              -H "Content-Type: application/json" \
              -H "x-robonito-api-key: $ROBONITO_API_KEY" \
              -d '{
              "suiteId": "2099b2b6-f5a3-45f3-9070-f0acb6691f0c",
              "circleciJobName": "$CIRCLE_JOB",
              "circleciBuildNumber": '$CIRCLE_BUILD_NUM'
            }'

workflows:
  robonito:
    jobs:
      - robonito-tests
